packages:
  - "apps/*"
  - "packages/*"

catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.1.1
  
  # TypeScript
  typescript: 5.9.3
  "@types/node": ^24.7.1
  "@types/react": ^18.2.61
  "@types/react-dom": ^18.2.19
  
  # Validation
  zod: ^3.24.1
  
  # Linting
  eslint: ^9.37.0
  
  # Testing
  jest: ^30.2.0
  "@jest/globals": ^30.2.0
  supertest: ^7.1.4
  "@types/supertest": ^6.0.3
  ts-jest: ^29.2.5
  
  # UI Libraries
  "lucide-react": ^0.545.0
  "tailwindcss": ^4.1.14
  "@tailwindcss/postcss": ^4.1.14
  
  # API Framework
  hono: ^4.9.11
  "@hono/node-server": ^1.19.5
  body-parser: ^2.2.0
  cors: ^2.8.5
  "@types/body-parser": ^1.19.6
  "@types/cors": ^2.8.19
  
  # Database
  drizzle-orm: ^0.44.6
  drizzle-kit: ^0.31.5
  pg: ^8.16.3
  "@types/pg": ^8.15.5
  
  # Authentication
  jsonwebtoken: ^9.0.2
  "@types/jsonwebtoken": ^9.0.10
  next-auth: ^4.24.11
  
  # Logging
  pino: ^10.0.0
  
  # Build Tools
  esbuild: ^0.25.10
  esbuild-register: ^3.6.0
  nodemon: ^3.1.10
  tsc-alias: ^1.8.16
  
  # Web Dependencies
  "@hookform/resolvers": ^3.9.1
  "@radix-ui/react-accordion": ^1.2.12
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-navigation-menu": ^1.2.14
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.6
  "@shadcn/ui": ^0.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  motion: ^12.23.24
  next-themes: ^0.4.6
  react-hook-form: ^7.65.0
  sonner: ^2.0.7
  swr: ^2.3.6
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.4.0
  
  # ESLint
  "@vercel/style-guide": ^5.2.0
  eslint-config-turbo: ^2.0.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-only-warn: ^1.1.0
  "@typescript-eslint/parser": ^7.1.0
  "@typescript-eslint/eslint-plugin": ^7.1.0
  "@next/eslint-plugin-next": ^14.1.1
  
  # Root Level
  dotenv: ^17.2.3
  vite-node: ^3.2.4
  prettier: ^3.6.2
  turbo: ^2.5.8